# Generated by Django 3.0.6 on 2021-08-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
    ]
