# Generated by Django 3.0.6 on 2021-08-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210812_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='', max_length=100, null=True),
        ),
    ]
