# Generated by Django 3.2.5 on 2021-10-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211010_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
