# Generated by Django 3.2.5 on 2021-10-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
    ]
