# Generated by Django 3.2.5 on 2021-10-10 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211010_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='reviews',
        ),
    ]
