# Generated by Django 3.2.5 on 2021-10-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_reviews'),
        ('reviews', '0002_reviews_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='product',
        ),
        migrations.AddField(
            model_name='reviews',
            name='preview',
            field=models.ManyToManyField(related_name='product_review', to='core.Product'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
