# Generated by Django 3.2.5 on 2021-10-10 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20211010_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='preview',
        ),
    ]
